version: "3.1"

services:
  mongo:
    container_name: cl_mongo
    build: ./docker/mongo
    restart: always
    ports:
      - "27018:27017"

networks:
  default:
    external:
      name: cl-dashboard