FROM mongo

ENV MONGO_INITDB_ROOT_USERNAME cl-dashboard
ENV MONGO_INITDB_ROOT_PASSWORD cl-dashboard

# To initialize Mongo on Docker Up
# ENV MONGO_INITDB_DATABASE admin
# ADD mongo-init.js /docker-entrypoint-initdb.d/